### ISSUE TITLE
problème de  binding ;-)

### ISSUE THREAD

**Issue by guersbru** [ChriGau/caplanpourmoi#133]
![xyaacecoei](https://user-images.githubusercontent.com/7116288/38515104-83736284-3c33-11e8-8102-478c09c8ce79.gif)

**Comment by ChriGau** [comment]
note to self

ajouter=

```
$('.update_slot').unbind();
$('.delete_slot').unbind();
```

dans le eventClick de `calendar.js`

**Comment by ChriGau** [comment]
fixed #88
