### ISSUE TITLE
Liste des sol ne s'affiche pas

### ISSUE THREAD

**Issue by guersbru** [ChriGau/caplanpourmoi#175]
Lorsqu'on est dans la page solution on ne peut pas cliquer sur l'entete de calcul pour faire apparaitre la liste des solutions calculées

**Comment by ChriGau** [comment]
j'avais cru voir que c'était lié à la position de mon
`<%= link_to "details", show_cs_details_path(@planning, computed_solution), { :class=>"btn-success" } %>`
dans le _list_computed_solutions.erb

**Comment by guersbru** [comment]
Tu as raison.. problème un peu à la con et pas si simple à résoudre. On ne peut pas avoir de lien nesté... pour ouvrir le panel bootstrap il faut un lien qui englobe l'entête à l'intérieur de cette en tête on veut mettre un autre lien donc ça marche pas....
Plusieurs solutions : 
* soit on fait du js on met un event listener sur l'entête et et lance la fonction js de bootstrap .collapse("show") sur l'élément portant l'id de la solution. 
* soit on fait un trick css ou notre balise de lien pour collapse le panel n'englobe pas le header mais est brother et on fait du positioning en absolute en jouant sur la profondeur des éléments
* soit on repense dès maintenant le design de cette page qui est déjà un peu tordue ;-)

**what do you think @ChriGau ?**

**Comment by ChriGau** [comment]
on repense le design!

**Comment by guersbru** [comment]
oups je me suis lancé dedans en mode js
