### ISSUE TITLE
refetch slots à la création 

### ISSUE THREAD

**Issue by guersbru** [ChriGau/caplanpourmoi#89]
Lors de la création des slots on recharge la page au lieu de ne faire que la requète ajax

**Comment by ChriGau** [comment]
réglé via pull request 88-patch-slots #130

**Comment by ChriGau** [comment]
dans skeleton.html.erb on load le JS de calendar.js

Dans calendar.js, on effectue les CRUD
- soit en affichant un simple_form (dans une modal) --> create ou update via le form
- soit en effectuant des requêtes ajax (cas de eventResize, eventDrop et click sur le bouton delete du form)
Dans tous les cas on repasse par le SlotsController qui renvoie vers le js des methodes CRUD correspondantes. Ces JS contiennent `  $('#calendar').fullCalendar( 'refetchEvents');` qui permet de recharger le calendar.
